### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by XxParkerGamesxX** [spigotpe-beta/SpigotPE#4]
todo in the feature 

- [ ] add MobAI
- [ ] add all blocks of 1.0 and 1.1 (and 1.2) (half done)
- [ ] support for 1.2 (COMING SOON)
- [ ] fix all BinaryStream\Binary bugs (almost fixt)
- [x] add DevTools
- [x] more fixes
- [x] add devtools folder loader and commands

**Comment by BlawoHD** [comment]
@caspervanneck Add DevTools?

**Comment by caspervanneck** [comment]
o yea almost vergat

**Comment by XxParkerGamesxX** [comment]
there fixed everything

**Comment by caspervanneck** [comment]
you cant do everyting @XxParkerGamesxX  1.2 isent auth yet
